### PR TITLE
Sdk vault integration

### PR DESCRIPTION
**Pull request by parthjindal-ibm**
### Description 
This pull request adds the support for secret retrieval from Vault. It adds a new module called vault, which when build produces a shadowJar which can be used a dependency in any other module.
### Changes 
- Implemented in rdb module for the informixDB configuration.
- Check the rdb/config/config-informix.yaml to see the configuration structure.
- DcConfig class implements the Vault functionality.
- vault shadowJar is present in the rdb/libs directory and added as a dependency in the rdb/build.gradle.

Note: Vault directory present in the internal directory.

### CODE REVIEW

**Comment by liurui-1** [comment]
Test failed at code: https://github.com/instana/otel-dc/blob/sdk-vault-integration/rdb/src/main/java/com/instana/dc/rdb/impl/informix/InformixDc.java#L23

If user does not define` "db.sequential.scan.count"`, then you will get an `NullPointerException`

**Review by liurui-1 — COMMENTED** [review]
Test failed at:
```
2024-06-28T01:49:11.346-0700 [DEBUG] [TestEventLogger] InformixDcTest > initializationError FAILED
2024-06-28T01:49:11.346-0700 [DEBUG] [TestEventLogger]     java.lang.NullPointerException
2024-06-28T01:49:11.346-0700 [DEBUG] [TestEventLogger]         at com.instana.dc.rdb.impl.informix.InformixDc.parseCustomAttributes(InformixDc.java:233)
2024-06-28T01:49:11.346-0700 [DEBUG] [TestEventLogger]         at com.instana.dc.rdb.impl.informix.InformixDc.<init>(InformixDc.java:70)
2024-06-28T01:49:11.346-0700 [DEBUG] [TestEventLogger]         at com.instana.dc.rdb.impl.informix.InformixDcTest.init(InformixDcTest.java:57)

```

**Comment by debnathbikram** [comment]
> Test failed at:
> 
> ```
> 2024-06-28T01:49:11.346-0700 [DEBUG] [TestEventLogger] InformixDcTest > initializationError FAILED
> 2024-06-28T01:49:11.346-0700 [DEBUG] [TestEventLogger]     java.lang.NullPointerException
> 2024-06-28T01:49:11.346-0700 [DEBUG] [TestEventLogger]         at com.instana.dc.rdb.impl.informix.InformixDc.parseCustomAttributes(InformixDc.java:233)
> 2024-06-28T01:49:11.346-0700 [DEBUG] [TestEventLogger]         at com.instana.dc.rdb.impl.informix.InformixDc.<init>(InformixDc.java:70)
> 2024-06-28T01:49:11.346-0700 [DEBUG] [TestEventLogger]         at com.instana.dc.rdb.impl.informix.InformixDcTest.init(InformixDcTest.java:57)
> ```

Hi @liurui-1 
Yes we are working on this and it is failing because of the java version mismatch which we are planning to raise by Monday EOD.

**Comment by liurui-1** [comment]
```
InformixDcTest > shouldCollectData() FAILED
    org.mockito.exceptions.verification.TooManyActualInvocations at InformixDcTest.java:79
```

**Review by liurui-1 — APPROVED** [review]
LGTM

**Pull request merged**
