### PR TITLE
Collect metrics from Traceloop instrumentation

### PR DESCRIPTION
**Pull request by jinsongo**
The PR is to implement the metrics collections from Traceloop instrumentation.

### CODE REVIEW

**Comment by jinsongo** [comment]
@liurui-1 @zhilee2008 Could you help to review the PR, thanks a lot!

**Comment by liurui-1** [comment]
There can be other implementations for LLM.
So, is it better to change the directory name `impl/llm` to be `impl/watsonx` ?

**Comment by jinsongo** [comment]
> Hi @jinsongo , There can be other implementations for LLM. So, is it better to change the directory name `impl/llm` to be `impl/watsonx` ?

@liurui-1 the LLM DC can handle the metrics from Traceloop instrumentations for both OpenAI and Watsonx that have the very similar semconv. Thanks.

**Review by liurui-1 — APPROVED** [review]
LGTM

**Pull request merged**
